task3：Yohohohohohoho
openbuildxyz/Web3-Frontend-Bootcamp pull request #1005
Opened 2024-06-30 11:13 UTC by Yahohohohohoho

## PR规范

注册的 PR，命名为 `init: user-name`，例如 `init: Beavnvvv`

提交 task 的 PR，命名为 `task[n]: user-name`，例如： `task0: Beavnvvv`

需要编写网页的 `task`，请在描述中上传效果截图。

**请不要把报名和提交TASK的内容合并到一起，也不要将多个TASK放到一起提交！**  
**请不要把报名和提交TASK的内容合并到一起，也不要将多个TASK放到一起提交！**  
**请不要把报名和提交TASK的内容合并到一起，也不要将多个TASK放到一起提交！**

2024-06-30 14:32 UTC, linghuccc commented
只需要最重要的 3 个合约文件，其他乱七八糟的不要 commit 进来

2024-06-30 15:03 UTC, linghuccc requested changes
只需要最重要的 3 个合约文件，其他用不到的文件不需要 commit 进来

2024-06-30 16:38 UTC, Yahohohohohoho commented
非必要文件已删除

2024-07-01 01:04 UTC, linghuccc requested changes
购买哈希写错了

2024-07-01 11:44 UTC, Yahohohohohoho commented
已改

2024-07-01 15:59 UTC, linghuccc approved these changes

2024-07-01 15:59 UTC, merged