task3
openbuildxyz/Web3-Frontend-Bootcamp pull request #1078
Opened 2024-07-04 07:41 UTC by warku123

## PR规范

注册的 PR，命名为 `init: user-name`，例如 `init: Beavnvvv`

提交 task 的 PR，命名为 `task[n]: user-name`，例如： `task0: Beavnvvv`

需要编写网页的 `task`，请在描述中上传效果截图。

**请不要把报名和提交TASK的内容合并到一起，也不要将多个TASK放到一起提交！**  
**请不要把报名和提交TASK的内容合并到一起，也不要将多个TASK放到一起提交！**  
**请不要把报名和提交TASK的内容合并到一起，也不要将多个TASK放到一起提交！**

2024-07-04 07:45 UTC, linghuccc requested changes
为什么你提交的任务是 “task3: JeremyZ”，而文件夹名却是 “warku123”，这 2 个应该是一样的 (github ID)，请检查，谢谢。

2024-07-04 07:47 UTC, linghuccc reviewed
listNFT 时未检查 price，但 buyNFT 时有检查，会造成逻辑错误，请复查，谢谢。

2024-07-04 07:49 UTC, linghuccc reviewed
买家和卖家，请使用不同地址，谢谢。

2024-07-05 07:36 UTC, warku123 commented
> 买家和卖家，请使用不同地址，谢谢。

已经修改完毕，使用两个account并且修改合约逻辑

2024-07-05 07:45 UTC, linghuccc approved these changes

2024-07-05 07:45 UTC, merged