task 3: posuihushui
openbuildxyz/Web3-Frontend-Bootcamp pull request #1127
Opened 2024-07-07 11:04 UTC by posuihushui

2024-07-12 12:28 UTC, linghuccc requested changes
1. PR 规范要求 “task3”，而不是 “task 3”；
2. function listNFT 里面， listings[tokenId] = Listing(msg.sender, nftContract, tokenId, price); 是错误的，应该是 listings[listingCounter]；
3. Buy NFT 之后，不删除 listing，如果下次同样的 NFT 再次 list，有被攻击的可能性（逻辑漏洞）；

请修改，谢谢。

2024-07-12 15:11 UTC, posuihushui commented
@linghuccc hi，已经修改listNFT和purchaseNFT的逻辑，但是purchaseNFT 依旧无法成功，可能是什么原因呢？
tx 如下：https://sepolia.etherscan.io/tx/0xb9c652d46329f313892e02cbb429408f598926e519145b3143edfb53b7acc4ee

2024-07-13 10:33 UTC, linghuccc commented
> @linghuccc hi，已经修改listNFT和purchaseNFT的逻辑，但是purchaseNFT 依旧无法成功，可能是什么原因呢？ tx 如下：https://sepolia.etherscan.io/tx/0xb9c652d46329f313892e02cbb429408f598926e519145b3143edfb53b7acc4ee

在 purchase NFT 之前，buyer 必须先 approve NFT contract 动用他的 ERC 20 token，才能 call purchase NFT function。
（顺带一提，你在 readme 里面写的微信号，搜不到）

2024-07-13 12:56 UTC, posuihushui commented
@linghuccc 已成功，确实是没有approve的原因。微信我设置隐私了~，我刚刚打开了~

2024-07-13 13:11 UTC, linghuccc approved these changes

2024-07-13 13:11 UTC, merged