task3: WonderfulWan8
openbuildxyz/Web3-Frontend-Bootcamp pull request #1177
Opened 2024-07-11 14:59 UTC by WonderfulWan8

2024-07-12 05:42 UTC, linghuccc requested changes
1. Task 3 的 PR 里面，请只修改 task3 文件夹的内容，不要修改其他内容，比如主文件夹的 readme 文件；
2. 你的合约部署没有成功，没有 list NFT，直接 Buy (哈希有问题)；

请修改，谢谢。

2024-07-13 13:57 UTC, WonderfulWan8 commented
您好，请问为什么部署成功了，但buyNFT会报错
https://sepolia.etherscan.io/tx/0xa4b4456e5a12d01592986eac535d9e947dc0c06e0dbf3d99dc8e1eb4811bddf4

2024-07-13 14:02 UTC, linghuccc commented
> 您好，请问为什么部署成功了，但buyNFT会报错 https://sepolia.etherscan.io/tx/0xa4b4456e5a12d01592986eac535d9e947dc0c06e0dbf3d99dc8e1eb4811bddf4

buy NFT 失败，一般是 2 个问题，1. buyer account 没有足够用于购买 NFT 的 ERC20 token； 2. buyer account 的 ERC20 token 没有 approve 给 nft market contract 去使用；
请审查。

2024-07-13 14:08 UTC, WonderfulWan8 commented
收到，感谢您的回复。
我做了如下操作，仍是交易失败，希望您能帮我check一下
1、从发行NFT账户往buyer account转了1000OBT
https://sepolia.etherscan.io/tx/0x1c169a78a914b22286eb8372e93d3928c009a5e51af773bba43f4c3f5544aa85
2、使用 buyer账户在 WEB3FRONTENDTOKEN 、NFTEXCHANGE  做了Approve操作
![image](https://github.com/user-attachments/assets/abc256a6-a713-4cf9-96c8-b8b909109f01)
https://sepolia.etherscan.io/tx/0x714f2289e218bd1542590ca694136e89b852efd2f21c76163b46ad377e5a06a5
https://sepolia.etherscan.io/tx/0x843ec5ef7577b9a304bd309f8959e1e675fd3719b0a319e6d1ddfa7618531293
3、再次使用buyer账户调用bufNFT方法 仍是交易失败
https://sepolia.etherscan.io/tx/0x1e4182270d0c9c4fe4011166b227bc41be22910841bc01557582107c82df5912

2024-07-13 14:19 UTC, linghuccc commented
> 收到，感谢您的回复。 我做了如下操作，仍是交易失败，希望您能帮我check一下 1、从发行NFT账户往buyer account转了1000OBT https://sepolia.etherscan.io/tx/0x1c169a78a914b22286eb8372e93d3928c009a5e51af773bba43f4c3f5544aa85 2、使用 buyer账户在 WEB3FRONTENDTOKEN 、NFTEXCHANGE 做了Approve操作 ![image](https://private-user-images.githubusercontent.com/96806061/348476486-abc256a6-a713-4cf9-96c8-b8b909109f01.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA4ODA1MTIsIm5iZiI6MTcyMDg4MDIxMiwicGF0aCI6Ii85NjgwNjA2MS8zNDg0NzY0ODYtYWJjMjU2YTYtYTcxMy00Y2Y5LTk2YzgtYjhiOTA5MTA5ZjAxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzEzVDE0MTY1MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA1MmQwN2YwOGViZWE3MzAxMzU1Njc2NjcxZDMzZGRiOGQwNDE3YzNkNDZhOGQ4ZDdkOWZlOGFiMDM3ZDgyYjImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.XLUR1z5LpOApvl5TFXjtwymnpnARPSh2ajSqBVc_Mgc) https://sepolia.etherscan.io/tx/0x714f2289e218bd1542590ca694136e89b852efd2f21c76163b46ad377e5a06a5 https://sepolia.etherscan.io/tx/0x843ec5ef7577b9a304bd309f8959e1e675fd3719b0a319e6d1ddfa7618531293 3、再次使用buyer账户调用bufNFT方法 仍是交易失败 https://sepolia.etherscan.io/tx/0x1e4182270d0c9c4fe4011166b227bc41be22910841bc01557582107c82df5912

已在 EVM 群回复，这里就不多写了。

2024-08-30 17:50 UTC, ourai commented
因超过截止时间（2024 年 7 月 16 日 23 时 59 分 59 秒）仍未修改问题，故视为放弃继续学习而暂且关掉 PR，若要继续学习就重新打开并做修改。

2024-08-30 17:50 UTC, closed without merging