task8:threshermagnus484159
openbuildxyz/Web3-Frontend-Bootcamp pull request #1212
Opened 2024-07-13 08:38 UTC by threshermagnus484159

2024-07-13 11:55 UTC, threshermagnus484159 commented
合约地址：0x95B282C030050026110c6bc22A88EE18561f8019
链接：https://explorer-testnet.morphl2.io/address/0x95B282C030050026110c6bc22A88EE18561f8019?tab=contract

2024-07-13 11:55 UTC, threshermagnus484159 commented
![image](https://github.com/user-attachments/assets/98c0cae5-214a-4763-8c73-08f2b19cbbeb)

2024-07-13 17:02 UTC, ourai requested changes
请部署到 Morph Holesky 测试网上并更新截图和地址。

2024-07-14 04:41 UTC, ourai approved these changes

2024-07-14 04:42 UTC, merged