Task3: newTap
openbuildxyz/Web3-Frontend-Bootcamp pull request #1223
Opened 2024-07-13 16:32 UTC by newTap

## PR规范

注册的 PR，命名为 `init: user-name`，例如 `init: Beavnvvv`

提交 task 的 PR，命名为 `task[n]: user-name`，例如： `task0: Beavnvvv`

需要编写网页的 `task`，请在描述中上传效果截图。

**请不要把报名和提交TASK的内容合并到一起，也不要将多个TASK放到一起提交！**  
**请不要把报名和提交TASK的内容合并到一起，也不要将多个TASK放到一起提交！**  
**请不要把报名和提交TASK的内容合并到一起，也不要将多个TASK放到一起提交！**

2024-07-14 02:22 UTC, linghuccc requested changes
1. task 的 PR，不可以更改该 task 文件夹外面的文件，比如 readme；
2. 购买成功后，应该将 listedNfts[nftContract][nftTokenId].sale 标记为 false；
3. ERC20 和 ERC721 可以这么写，但没必要，可以参阅其他同学的代码（本次任务不要求修改）

请改正 1，2 项，谢谢。

2024-07-14 02:42 UTC, newTap commented
感谢回复

2024-07-15 14:57 UTC, linghuccc requested changes
购买 NFT 的交易哈希有误，请检查，谢谢。

2024-07-17 12:27 UTC, linghuccc requested changes
买家和卖家请使用不同地址，谢谢。

2024-07-19 00:56 UTC, linghuccc approved these changes

2024-07-19 00:56 UTC, merged