task9：threshermagnus484159
openbuildxyz/Web3-Frontend-Bootcamp pull request #1243
Opened 2024-07-14 10:14 UTC by threshermagnus484159

2024-07-14 13:36 UTC, ourai requested changes
The Graph 的 URL 要 `api.*` 开头的

2024-07-15 01:12 UTC, ourai requested changes
合约没有交互记录，无法验证

2024-07-15 13:27 UTC, threshermagnus484159 commented
ok啦，现在可以了

2024-07-18 04:05 UTC, ourai approved these changes

2024-07-18 04:07 UTC, merged