task9: DeJeune
openbuildxyz/Web3-Frontend-Bootcamp pull request #1320
Opened 2024-07-15 15:22 UTC by DeJeune

## PR规范

注册的 PR，命名为 `init: user-name`，例如 `init: Beavnvvv`

提交 task 的 PR，命名为 `task[n]: user-name`，例如： `task0: Beavnvvv`

需要编写网页的 `task`，请在描述中上传效果截图。

**请不要把报名和提交TASK的内容合并到一起，也不要将多个TASK放到一起提交！**  
**请不要把报名和提交TASK的内容合并到一起，也不要将多个TASK放到一起提交！**  
**请不要把报名和提交TASK的内容合并到一起，也不要将多个TASK放到一起提交！**

2024-07-18 05:54 UTC, ourai requested changes
你这提交什么情况？

2024-07-18 13:40 UTC, ourai requested changes
请看「Files changed」，仍然有很多问题，如果处理不好，建议拉新分支重新提交 task 9 的文件并发起 PR，在新 PR 描述里面附上这个 PR 链接说明情况。

2024-07-18 14:46 UTC, DeJeune commented
> 请看「Files changed」，仍然有很多问题，如果处理不好，建议拉新分支重新提交 task 9 的文件并发起 PR，在新 PR 描述里面附上这个 PR 链接说明情况。

已经改好

2024-07-19 02:06 UTC, DeJeune commented
> task9 提交 PR 注意点：
> 
> 1. 截图要有子图设置信息那页（Details）；
> 2. 要有子图链接且 URL 是 api.* 开头的；
> 3. 合约除了创建之外要有其他交互记录；
> 4. 子图索引完成率要 100%。

已更新相应描述

2024-07-19 14:33 UTC, ourai approved these changes

2024-07-19 14:33 UTC, merged