task3: fragrans-maotou
openbuildxyz/Web3-Frontend-Bootcamp pull request #1340
Opened 2024-07-28 01:41 UTC by fragrans-maotou

将task3、task4、task5 功能写到了这个合约中。

2024-07-29 02:52 UTC, fragrans-maotou commented
该合约可以实现task3任务。

2024-08-01 01:36 UTC, linghuccc requested changes
NFT Market 合约，在 constructor 里面不应该指定 ERC721 的合约，请修改，谢谢。

2024-08-01 02:21 UTC, fragrans-maotou commented
> NFT Market合约，在构造函数里面不应该指定ERC721的合约，请修改，谢谢。

谢谢您的指点，我再合约里修改与添加了一下代码，

```
// 自由的设置ERC721合约地址，不在指定一个Address
  function setNFT721Contract(address _nft721Contract) external onlyOwner {
      nft721Token = IERC721(_nft721Contract);
  }
```

让我对市场合约的理解又近了一步。(*^_^*)。

如果修改不符合，请再次提出 更改任务。

2024-08-03 06:16 UTC, linghuccc commented
> > NFT Market合约，在构造函数里面不应该指定ERC721的合约，请修改，谢谢。
> 
> 谢谢您的指点，我再合约里修改与添加了一下代码，
> 
> ```
> // 自由的设置ERC721合约地址，不在指定一个Address
>   function setNFT721Contract(address _nft721Contract) external onlyOwner {
>       nft721Token = IERC721(_nft721Contract);
>   }
> ```
> 
> 让我对市场合约的理解又近了一步。(_^_^_)。
> 
> 如果修改不符合，请再次提出 更改任务。

你理解了，但还不够。严格来说，你的合约不符合一个 NFT Market 的要求，但是作为一个作业，我觉得可以通过。建议参考一下其他同学的代码，加深一下理解。谢谢。

2024-08-03 06:16 UTC, linghuccc approved these changes

2024-08-03 06:17 UTC, merged

2024-08-04 03:52 UTC, fragrans-maotou commented
> > > NFT Market合约，在构造函数里面不应该指定ERC721的合约，请修改，谢谢。
> > 
> > 
> > 谢谢您的指点，我再合约里修改与添加了一下代码，
> > ```
> > // 自由的设置ERC721合约地址，不在指定一个Address
> >   function setNFT721Contract(address _nft721Contract) external onlyOwner {
> >       nft721Token = IERC721(_nft721Contract);
> >   }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 让我对市场合约的理解又近了一步。(_^_^_)。
> > 如果修改不符合，请再次提出 更改任务。
> 
> 你理解了，但还不够。严格来说，你的合约不符合一个 NFT Market 的要求，但是作为一个作业，我觉得可以通过。建议参考一下其他同学的代码，加深一下理解。谢谢。

谢谢指导，我去看看 (*^_^*)