Task7：fragrans-maotou
openbuildxyz/Web3-Frontend-Bootcamp pull request #1354
Opened 2024-08-02 05:57 UTC by fragrans-maotou

2024-08-02 13:21 UTC, ourai requested changes

2024-08-02 13:21 UTC, ourai commented on members/fragrans-maotou/task7/aspect/index.ts
> +    const blockTimeBytes = sys.hostApi.runtimeContext.get('block.header.number');
`block.header.timestamp`

2024-08-03 09:49 UTC, fragrans-maotou commented on members/fragrans-maotou/task7/aspect/index.ts
> +    const blockTimeBytes = sys.hostApi.runtimeContext.get('block.header.number');
好的，麻烦您啦，我这就去修改 (*^_^*) 。

2024-08-03 09:57 UTC, fragrans-maotou commented on members/fragrans-maotou/task7/aspect/index.ts
> +    const blockTimeBytes = sys.hostApi.runtimeContext.get('block.header.number');
> `block.header.timestamp`
已修改，感谢指正!

2024-08-03 12:15 UTC, ourai approved these changes

2024-08-03 12:15 UTC, merged