task1: justice010
openbuildxyz/Web3-Frontend-Bootcamp pull request #1387
Opened 2024-09-17 16:59 UTC by justice010

2024-10-01 03:24 UTC, ourai requested changes
![image](https://github.com/user-attachments/assets/0ffba5b6-340b-41d7-bee0-32da14bf23cb)
启动后报错。请先好好自测下功能完整性。

2024-10-01 07:26 UTC, justice010 commented
![image](https://github.com/user-attachments/assets/acbe0612-8a69-4722-8c56-82c39c1e2712)
![image](https://github.com/user-attachments/assets/2cc57886-6c98-427f-881a-87c6fffc4d33)

2024-10-02 02:11 UTC, ourai requested changes

2024-10-02 02:11 UTC, ourai commented on members/justice010/task1/todo-app/src/App.jsx
> +import { AddToDo } from "./AddTodo";
文件名大小写错误

2024-10-02 11:51 UTC, justice010 commented on members/justice010/task1/todo-app/src/App.jsx
> +import { AddToDo } from "./AddTodo";
改好了，麻烦再看看，辛苦欧雷哥

2024-10-02 16:11 UTC, ourai approved these changes

2024-10-02 16:11 UTC, merged