feat Jason readme
openbuildxyz/Web3-Frontend-Bootcamp pull request #17
Opened 2024-06-04 05:48 UTC by JasonStu

2024-06-05 12:12 UTC, restartgr requested changes
文件格式有误，麻烦调整下，都放到自己id的文件夹下

2024-06-05 12:30 UTC, JasonStu commented
> 文件格式有误，麻烦调整下，都放到自己id的文件夹下

已经修改完成，麻烦再看看。

2024-06-05 12:31 UTC, restartgr requested changes
不要删除别人的文件，麻烦还原下

2024-06-05 12:53 UTC, JasonStu commented
> 不要删除别人的文件，麻烦还原下

抱歉，以为那个是我自己产生的文件，我重新提了pr https://github.com/openbuildxyz/Web3-Frontend-Bootcamp/pull/163
163 合并后我关闭这个pr，谢谢你，麻烦了

2024-06-06 02:22 UTC, restartgr commented
合并了#163 我关闭这个pr了

2024-06-06 02:22 UTC, closed without merging