init: barry
openbuildxyz/Web3-Frontend-Bootcamp pull request #232
Opened 2024-06-06 10:47 UTC by haobarry

## PR规范

注册的 PR，命名为 `init: user-name`，例如 `init: Beavnvvv`

提交 task 的 PR，命名为 `task[n]: user-name`，例如： `task0: Beavnvvv`

需要编写网页的 `task`，请上传效果截图。

**请不要把报名和提交TASK的内容合并到一起，也不要将多个TASK放到一起提交！**  
**请不要把报名和提交TASK的内容合并到一起，也不要将多个TASK放到一起提交！**  
**请不要把报名和提交TASK的内容合并到一起，也不要将多个TASK放到一起提交！**

2024-06-06 11:49 UTC, haobarry commented
麻烦帮忙和一下 要不提交不后续pr

2024-06-07 01:47 UTC, ourai requested changes
把 task1 拆出去另外提交专属 PR，详见 https://github.com/openbuildxyz/Web3-Frontend-Bootcamp#%E5%BC%80%E5%90%AF%E5%A4%9A%E4%B8%AA-pr

2024-06-07 03:05 UTC, ourai approved these changes

2024-06-07 03:05 UTC, merged

2024-06-07 03:07 UTC, haobarry commented
@ourai 现在可以合并了
原来你是官方的 我以为你是学员

2024-06-07 03:16 UTC, ourai commented
> @ourai 现在可以合并了 原来你是官方的 我以为你是学员

学员兼志愿者😄 @haobarry