task1: caocanx
openbuildxyz/Web3-Frontend-Bootcamp pull request #244
Opened 2024-06-06 13:44 UTC by caocanx

2024-06-11 13:50 UTC, caocanx commented
为什么被标记为无效，我是按照要求完成的呀？

2024-06-11 13:59 UTC, caocanx commented
运行效果图
![CleanShot 2024-06-11 at 21 58 46@2x](https://github.com/openbuildxyz/Web3-Frontend-Bootcamp/assets/15025287/d5e656e6-7d1a-48da-818e-3ce56cbd0867)

2024-06-13 07:48 UTC, ourai requested changes
![image](https://github.com/openbuildxyz/Web3-Frontend-Bootcamp/assets/562589/4105d6f4-b196-428e-8323-6a3a26310948)
![image](https://github.com/openbuildxyz/Web3-Frontend-Bootcamp/assets/562589/eb02d3a9-a937-407f-9372-a6a559b618df)
请仔细检查并自测功能

2024-06-13 08:05 UTC, caocanx commented
> ![image](https://private-user-images.githubusercontent.com/562589/339268761-4105d6f4-b196-428e-8323-6a3a26310948.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgyNjYwNzAsIm5iZiI6MTcxODI2NTc3MCwicGF0aCI6Ii81NjI1ODkvMzM5MjY4NzYxLTQxMDVkNmY0LWIxOTYtNDI4ZS04MzIzLTZhM2EyNjMxMDk0OC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYxM1QwODAyNTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04Njc2YzE1MTczNDkzZjllYmJhZjY0ZmI2MGU2MWY3NWViMDIxMjYxZjJjMDJiN2RkZTM5MjRjZGYxNGI1MDA0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Xq8dufw_j9ox-98GfyRK3u_CP6cGmtmDfcnivGjJb60) ![image](https://private-user-images.githubusercontent.com/562589/339268839-eb02d3a9-a937-407f-9372-a6a559b618df.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgyNjYwNzAsIm5iZiI6MTcxODI2NTc3MCwicGF0aCI6Ii81NjI1ODkvMzM5MjY4ODM5LWViMDJkM2E5LWE5MzctNDA3Zi05MzcyLWE2YTU1OWI2MThkZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYxM1QwODAyNTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jNjNmNDZkM2RhYzY2MTBlZDY3MzdmODYwMmRlZWMzMjc3NDY4ODhhMGE2YWVlOGY0NWY0ZjI5ZTAwN2NhOTQzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.9M0Oq72VZhXZgDTgHYRTqzczgqxdVktAR7LUfyA84-0) 请仔细检查并自测功能

抱歉，我已自测并修复

2024-06-13 14:01 UTC, ourai approved these changes

2024-06-13 14:02 UTC, merged