task2: barry
openbuildxyz/Web3-Frontend-Bootcamp pull request #305
Opened 2024-06-07 08:30 UTC by haobarry

## PR规范

注册的 PR，命名为 `init: user-name`，例如 `init: Beavnvvv`

提交 task 的 PR，命名为 `task[n]: user-name`，例如： `task0: Beavnvvv`

需要编写网页的 `task`，请上传效果截图。

**请不要把报名和提交TASK的内容合并到一起，也不要将多个TASK放到一起提交！**  
**请不要把报名和提交TASK的内容合并到一起，也不要将多个TASK放到一起提交！**  
**请不要把报名和提交TASK的内容合并到一起，也不要将多个TASK放到一起提交！**

2024-06-13 08:12 UTC, ourai requested changes
只提交 task 2 相关文件

2024-06-18 07:53 UTC, haobarry commented
好了  重新提交了

2024-06-18 08:51 UTC, ourai requested changes
任务文件夹名应为 `task2`

2024-06-20 01:39 UTC, merged

2024-06-20 04:13 UTC, zhangloveyan commented
修改文件夹名称 taks2 -> task2 @haobarry