task2:Jasmiiinn
openbuildxyz/Web3-Frontend-Bootcamp pull request #311
Opened 2024-06-07 09:02 UTC by Jasmiiinn

2024-06-07 09:10 UTC, Jasmiiinn commented
task2 ：Jasmiiinn

2024-06-13 08:13 UTC, ourai requested changes
请按规范拆分与提交 PR：https://github.com/openbuildxyz/Web3-Frontend-Bootcamp#%E5%8F%82%E4%B8%8E%E6%96%B9%E5%BC%8F

2024-06-20 01:40 UTC, zhangloveyan commented
![image](https://github.com/openbuildxyz/Web3-Frontend-Bootcamp/assets/19526982/98533b77-9762-44f6-905d-b753094e9069)
选择错误。
另外简答用自己话回答，不要 gpt 生成

2024-08-30 17:09 UTC, ourai commented
因超过截止时间（2024 年 7 月 16 日 23 时 59 分 59 秒）仍未修改问题，故视为放弃继续学习而暂且关掉 PR，若要继续学习就重新打开并做修改。

2024-08-30 17:09 UTC, closed without merging