init:marukowanzi
openbuildxyz/Web3-Frontend-Bootcamp pull request #354
Opened 2024-06-08 10:16 UTC by marukowanzi

## PR规范

注册的 PR，命名为 `init: user-name`，例如 `init: Beavnvvv`

提交 task 的 PR，命名为 `task[n]: user-name`，例如： `task0: Beavnvvv`

需要编写网页的 `task`，请上传效果截图。

**请不要把报名和提交TASK的内容合并到一起，也不要将多个TASK放到一起提交！**  
**请不要把报名和提交TASK的内容合并到一起，也不要将多个TASK放到一起提交！**  
**请不要把报名和提交TASK的内容合并到一起，也不要将多个TASK放到一起提交！**

2024-06-08 10:27 UTC, BBK912 requested changes
##任务提交 部分 需要删除  
作业提交 参考 https://github.com/openbuildxyz/Web3-Frontend-Bootcamp?tab=readme-ov-file#%E8%AF%BE%E5%90%8E%E4%BD%9C%E4%B8%9A

2024-06-08 10:31 UTC, marukowanzi commented
> ##任务提交 部分 需要删除 作业提交 参考 https://github.com/openbuildxyz/Web3-Frontend-Bootcamp?tab=readme-ov-file#%E8%AF%BE%E5%90%8E%E4%BD%9C%E4%B8%9A

请问“任务提交部分需要删除”是什么意思。哪个是任务提交部分

2024-06-08 10:34 UTC, marukowanzi commented
> ##任务提交 部分 需要删除 作业提交 参考 https://github.com/openbuildxyz/Web3-Frontend-Bootcamp?tab=readme-ov-file#%E8%AF%BE%E5%90%8E%E4%BD%9C%E4%B8%9A

我的过程是fork了git clone到本地，然后复制了一个id文件夹仅修改了readme中的内容

2024-06-08 10:39 UTC, marukowanzi commented
懂了，已修改完成请查收

2024-06-12 03:31 UTC, ourai requested changes
GitHub ID 就是 `marukowanzi`，不是数字那个，请更改一下。

2024-08-30 17:10 UTC, ourai commented
因超过截止时间（2024 年 7 月 16 日 23 时 59 分 59 秒）仍未修改问题，故视为放弃继续学习而暂且关掉 PR，若要继续学习就重新打开并做修改。

2024-08-30 17:10 UTC, closed without merging