task1: TLwen114514
openbuildxyz/Web3-Frontend-Bootcamp pull request #364
Opened 2024-06-08 16:47 UTC by TLwen114514

任务1
第一次提交

2024-06-09 09:16 UTC, zhengqiuwan commented
> 任务1 第一次提交

需要提供一下代码的运行截图

2024-06-10 06:13 UTC, TLwen114514 commented
@zhengqiuwan 已补充，请求合并

2024-06-13 08:34 UTC, ourai requested changes
任务文件夹名应是 `task1` 而非 `task01`

2024-06-16 03:18 UTC, ourai requested changes
刷新后数据消失

2024-06-18 06:18 UTC, TLwen114514 commented
@ourai  修改了，请欧雷哥看看

2024-06-18 09:25 UTC, ourai approved these changes

2024-06-18 09:26 UTC, merged