task[1]: coolberwin
openbuildxyz/Web3-Frontend-Bootcamp pull request #382
Opened 2024-06-09 10:56 UTC by coolberwin

完成 task1 构建todoList

2024-06-12 08:52 UTC, coolberwin commented
why is invalid?

2024-06-13 08:51 UTC, ourai requested changes
刷新后数据没有回显

2024-06-13 09:17 UTC, coolberwin commented
ok 我查下bug

2024-06-21 02:15 UTC, ourai approved these changes

2024-06-21 02:16 UTC, merged