task1: lulu546
openbuildxyz/Web3-Frontend-Bootcamp pull request #434
Opened 2024-06-10 15:26 UTC by lulu546

## PR规范

注册的 PR，命名为 `init: user-name`，例如 `init: Beavnvvv`

提交 task 的 PR，命名为 `task[n]: user-name`，例如： `task0: Beavnvvv`

需要编写网页的 `task`，请上传效果截图。

**请不要把报名和提交TASK的内容合并到一起，也不要将多个TASK放到一起提交！**  
**请不要把报名和提交TASK的内容合并到一起，也不要将多个TASK放到一起提交！**  
**请不要把报名和提交TASK的内容合并到一起，也不要将多个TASK放到一起提交！**  

![image](https://github.com/openbuildxyz/Web3-Frontend-Bootcamp/assets/87536202/4f9ca609-37ac-4bee-9368-afd38c3a2594)
![image](https://github.com/openbuildxyz/Web3-Frontend-Bootcamp/assets/87536202/e6bf3bb2-f650-4e83-9319-e5d7d8877fe1)
![image](https://github.com/openbuildxyz/Web3-Frontend-Bootcamp/assets/87536202/d9598e92-404d-4715-9ac8-eaaaf88ec706)
![image](https://github.com/openbuildxyz/Web3-Frontend-Bootcamp/assets/87536202/32a87722-15f2-4e18-86cf-2b2f36099018)
![image](https://github.com/openbuildxyz/Web3-Frontend-Bootcamp/assets/87536202/7e195aa9-abb9-4bee-ab2b-006171023da9)
![image](https://github.com/openbuildxyz/Web3-Frontend-Bootcamp/assets/87536202/3d7350ca-a502-4802-9391-03756e5e31bb)
![image](https://github.com/openbuildxyz/Web3-Frontend-Bootcamp/assets/87536202/97d67eca-a3e9-4a5a-b32f-f42b1e410a18)

2024-06-11 04:15 UTC, ourai requested changes
请用 Vite + 本地存储实现

2024-06-11 04:21 UTC, lulu546 commented
> 请用 Vite + 本地存储实现

用了json-server，实际上它就是本地存储实现的。

2024-06-11 04:59 UTC, ourai commented
这里的「本地存储」是指浏览器的机制，不是 Node.js，这不是前端开发。

2024-06-11 08:52 UTC, lulu546 commented
> 这里的「本地存储」是指浏览器的机制，不是 Node.js 中的 FS，这不是前端开发，task 1 考察的是前端开发技能。

OKOK，理解了，我将Next.js转成了React框架，使用了Vite打包，存储数据使用的浏览器存储，已提交。

2024-06-12 02:05 UTC, ourai requested changes
没有完成状态标记功能

2024-06-12 04:26 UTC, lulu546 commented
![image](https://github.com/openbuildxyz/Web3-Frontend-Bootcamp/assets/87536202/f35b9b74-5927-45fe-8bbe-679271a8340d)
对不起耽误您时间了，实在不好意思，我重新检查了一遍我的任务，确保这次功能都已完成QAQ，最新版已提交

> 没实现完成状态标记功能

2024-06-12 05:36 UTC, ourai requested changes
<img width="1483" alt="image" src="https://github.com/openbuildxyz/Web3-Frontend-Bootcamp/assets/562589/583ac23d-6323-4150-ab66-bbd068edf7d2">

2024-06-12 06:05 UTC, lulu546 commented
> <img alt="image" width="1483" src="https://private-user-images.githubusercontent.com/562589/338835463-583ac23d-6323-4150-ab66-bbd068edf7d2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgxNzI1MDcsIm5iZiI6MTcxODE3MjIwNywicGF0aCI6Ii81NjI1ODkvMzM4ODM1NDYzLTU4M2FjMjNkLTYzMjMtNDE1MC1hYjY2LWJiZDA2OGVkZjdkMi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYxMlQwNjAzMjdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lMTljYjhiNzFiNTJhODY5MmJjYjcxYWNiOTAxNDhiMjBhMWNhOTBjYWM4NWJiMGEwYmJjYTQwNTc3N2ZmNzZiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.ugWRw-rJUyIpZusiyB2Z4ccTCzus78rfMV2WvEEbYsI">

实在不好意思，下次一定先自己拉取运行一下。眼睛不好没看出大小写区别，现在拉取过后正常运行了。

2024-06-12 07:00 UTC, ourai requested changes
标记为完成之后还得支持反向标记取消已完成的状态呀。做完 task 后先对照要求逐条自测下。

2024-06-12 16:57 UTC, lulu546 commented
![image](https://github.com/openbuildxyz/Web3-Frontend-Bootcamp/assets/87536202/7b235704-7292-4c0d-8b14-403f4a12b1fb)

# task1自测  
项目初始化  
[ x ] 使用 Create-vite 初始化你的项目。  
[ x ] 设置项目结构，创建必要的文件和文件夹。  
创建组件  
[ x ] App 组件：作为应用的根组件。(已创建)   
[ x ] Header 组件：展示应用标题。(已创建)  
[ x ] ToDoList 组件：展示所有待办事项。(已创建)  
[ x ] ToDoItem 组件：展示单个待办事项。(已创建)  
[ x ] AddToDo  组件：包含一个输入框和添加按钮，用于添加新的待办事项。(已创建，命名为AddTask)  
实现功能  
[ x ] 用户可以通过输入框输入待办事项，并点击按钮进行添加。(功能已完成)    
[ x ] 删除待办事项：每个待办事项旁边有一个删除按钮，点击后可以删除该事项。(功能已完成)  
[ x ] 标记完成：用户可以通过点击待办事项，标记其为已完成或未完成。(功能已完成)  
[ x ] 保存到本地存储：使用 useEffect 将待办事项保存到本地存储，并在页面刷新时恢复。(功能已完成，增删改操作会刷新全局变量进而读取数据)  
使用状态管理  
[ x ] 使用 useState 管理待办事项列表和输入框的状态。(使用)  
使用 Hooks  
[ x ] 使用 useState 管理组件的状态。(使用)  
[ x ] 使用 useEffect 实现本地存储的保存和恢复功能。(使用)  


# 提交拉取测试
已通过

> 标记为完成之后还得支持反向标记取消已完成的状态呀。做完 task 后先对照要求逐条自测下。

2024-06-13 02:18 UTC, ourai approved these changes

2024-06-13 02:20 UTC, merged