task1: hundren
openbuildxyz/Web3-Frontend-Bootcamp pull request #496
Opened 2024-06-11 16:11 UTC by hundren

[在线预览](https://todolist-two-blush.vercel.app/)
![screenshot-todolist-two-blush vercel app-2024 06 11-23_56_48](https://github.com/openbuildxyz/Web3-Frontend-Bootcamp/assets/4225570/7f7755b1-2cff-44b3-a7b0-8b9f641a6e33)

2024-06-12 06:31 UTC, ourai requested changes
数据刷新后消失

2024-06-13 02:33 UTC, ourai requested changes
刷新后数据还是会消失啊，请在提交前好好自测下。

2024-06-13 02:47 UTC, hundren commented
你好，需求是：保存到本地存储：使用 useEffect 将待办事项保存到本地存储，并在页面刷新时恢复。
我第一版就是刷新后恢复本地存储数据的，第二次commit才把这个方法删掉的。
**需求歧义点是：刷新后想恢复到没添加的初始状态还是想恢复本地存储的数据，刷新数据要想消失还是恢复**

2024-06-13 06:27 UTC, ourai commented
> 你好，需求是：保存到本地存储：使用 useEffect 将待办事项保存到本地存储，并在页面刷新时恢复。 我第一版就是刷新后恢复本地存储数据，第二次commit才把这个方法删掉的。 **需求歧义点是：刷新后想恢复到没添加的初始状态还是想恢复本地存储的数据，刷新数据想要消失还是不消失**

需求是要在刷新页面后回显刷新前的数据状态，你删之后和之前我在测试时都没正常回显。

2024-06-13 06:49 UTC, hundren commented
https://github.com/openbuildxyz/Web3-Frontend-Bootcamp/assets/4225570/6605577e-93ea-4451-b70b-aae6c6cbecaf

是要这个效果吗

2024-06-13 10:00 UTC, ourai approved these changes

2024-06-13 10:00 UTC, merged