task1: Mika-Lahtinen
openbuildxyz/Web3-Frontend-Bootcamp pull request #515
Opened 2024-06-12 06:39 UTC by Mika-Lahtinen

## Task1: Mika-Lahtinen

- 项目初始化
![屏幕截图 2024-06-12 143401](https://github.com/openbuildxyz/Web3-Frontend-Bootcamp/assets/36355287/7aaee97b-5323-4d49-94f2-dda191428df9)

- 添加todo条目
![屏幕截图 2024-06-12 143528](https://github.com/openbuildxyz/Web3-Frontend-Bootcamp/assets/36355287/88489602-694a-49b1-b1d6-b0a362b3157d)

- 删除已完成todo条目
![屏幕截图 2024-06-12 143608](https://github.com/openbuildxyz/Web3-Frontend-Bootcamp/assets/36355287/11356de8-39b7-45db-84b6-921fd509c8a3)

2024-06-13 12:22 UTC, ourai requested changes
刷新后数据消失了

2024-06-13 15:05 UTC, Mika-Lahtinen commented
Fixed errors when refreshing pages.

2024-06-14 03:01 UTC, ourai requested changes
又不能删除了。按任务要求把功能都自测下。

2024-07-08 11:01 UTC, Mika-Lahtinen commented
重新编写了全部模块的代码，并按照题目要求均进行了测试

2024-07-08 23:56 UTC, ourai approved these changes

2024-07-08 23:56 UTC, merged