task2: Caseyz
openbuildxyz/Web3-Frontend-Bootcamp pull request #553
Opened 2024-06-13 07:56 UTC by Caseyz

2024-06-15 18:06 UTC, majoson-chen commented
查资料也要用点心

2024-06-15 18:07 UTC, majoson-chen requested changes
修改答案

2024-06-18 02:30 UTC, Georgiafab commented
图片没有体现出来在openbuild上绑定了钱包，只能看出来连接网站了

2024-08-30 17:19 UTC, ourai commented
因超过截止时间（2024 年 7 月 16 日 23 时 59 分 59 秒）仍未修改问题，故视为放弃继续学习而暂且关掉 PR，若要继续学习就重新打开并做修改。

2024-08-30 17:19 UTC, closed without merging