报名
openbuildxyz/Web3-Frontend-Bootcamp pull request #58
Opened 2024-06-04 12:24 UTC by tzy168

2024-06-08 18:58 UTC, zhengqiuwan commented on members/tzy168/task2/task2.md
> +安装一个 WEB3 钱包，创建账户后与 [openbuild.xyz](https://openbuild.xyz/profile) 进行绑定，截图后文件命名为 `./bind-wallet.jpg`.
task2未完成

2024-06-09 01:34 UTC, tzy168 commented on members/tzy168/task2/task2.md
> +安装一个 WEB3 钱包，创建账户后与 [openbuild.xyz](https://openbuild.xyz/profile) 进行绑定，截图后文件命名为 `./bind-wallet.jpg`.
这个pr只提交task1，我忘记创建分支了

2024-06-10 12:19 UTC, tzy168 commented on members/tzy168/task2/task2.md
> +安装一个 WEB3 钱包，创建账户后与 [openbuild.xyz](https://openbuild.xyz/profile) 进行绑定，截图后文件命名为 `./bind-wallet.jpg`.
完成task2

2024-06-12 12:19 UTC, ourai requested changes
请按规范拆分与提交 PR：https://github.com/openbuildxyz/Web3-Frontend-Bootcamp?tab=readme-ov-file#%E5%8F%82%E4%B8%8E%E6%96%B9%E5%BC%8F

2024-06-15 16:29 UTC, closed without merging