task3: zpjayyy
openbuildxyz/Web3-Frontend-Bootcamp pull request #589
Opened 2024-06-14 01:07 UTC by zpjayyy

## PR规范

注册的 PR，命名为 `init: user-name`，例如 `init: Beavnvvv`

提交 task 的 PR，命名为 `task[n]: user-name`，例如： `task0: Beavnvvv`

需要编写网页的 `task`，请在描述中上传效果截图。

**请不要把报名和提交TASK的内容合并到一起，也不要将多个TASK放到一起提交！**  
**请不要把报名和提交TASK的内容合并到一起，也不要将多个TASK放到一起提交！**  
**请不要把报名和提交TASK的内容合并到一起，也不要将多个TASK放到一起提交！**

2024-06-14 05:03 UTC, ourai requested changes
只能提交自己文件夹中的

2024-06-14 05:11 UTC, zpjayyy commented
不好意思，已经移除了部署时的依赖文件。

2024-07-01 01:28 UTC, linghuccc requested changes
task3 只需要提交最主要的 3 份合约文件和上架NFT、购买NFT的交易哈希，请不要提交其他无关文件，谢谢

2024-07-01 02:04 UTC, ourai approved these changes

2024-07-11 06:00 UTC, zpjayyy commented
调整好了，只保留了合约文件，以及交易hash @linghuccc l

2024-07-12 05:29 UTC, linghuccc approved these changes

2024-07-12 05:30 UTC, merged