task2: zhangmo8
openbuildxyz/Web3-Frontend-Bootcamp pull request #607
Opened 2024-06-14 07:21 UTC by zhangmo8

## PR规范

注册的 PR，命名为 `init: user-name`，例如 `init: Beavnvvv`

提交 task 的 PR，命名为 `task[n]: user-name`，例如： `task0: Beavnvvv`

需要编写网页的 `task`，请在描述中上传效果截图。

**请不要把报名和提交TASK的内容合并到一起，也不要将多个TASK放到一起提交！**  
**请不要把报名和提交TASK的内容合并到一起，也不要将多个TASK放到一起提交！**  
**请不要把报名和提交TASK的内容合并到一起，也不要将多个TASK放到一起提交！**

2024-06-16 08:22 UTC, majoson-chen requested changes

2024-06-16 08:22 UTC, majoson-chen commented on members/zhangmo8/task2/02_Blockchain_Basic.md
> +- [x] 一个私钥对应多个地址
错误

2024-06-16 08:22 UTC, majoson-chen commented on members/zhangmo8/task2/02_Blockchain_Basic.md
> +在预设条件满足时，智能合约可以自动执行，无需中间方参与。
错误，修改

2024-06-17 02:51 UTC, zhangmo8 commented on members/zhangmo8/task2/02_Blockchain_Basic.md
> +- [x] 一个私钥对应多个地址
fix，但不知道是否正确

2024-06-19 03:47 UTC, zhangloveyan commented
![image](https://github.com/openbuildxyz/Web3-Frontend-Bootcamp/assets/19526982/d08f1dea-3a9d-4f39-9c8b-695518dd74d5)
多选漏选

钱包请截取这个路径下的
profile -> social profiles  -> wallet 的截图

2024-06-19 04:04 UTC, zhangmo8 commented
> ![image](https://private-user-images.githubusercontent.com/19526982/340905090-d08f1dea-3a9d-4f39-9c8b-695518dd74d5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg3Njk5NzUsIm5iZiI6MTcxODc2OTY3NSwicGF0aCI6Ii8xOTUyNjk4Mi8zNDA5MDUwOTAtZDA4ZjFkZWEtM2E5ZC00ZjM5LTljOGItNjk1NTE4ZGQ3NGQ1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjE5VDA0MDExNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU3YWQ4MmI5OGQ5ZTEyMGYyMDVmMTNlYmM2YmYzNWM1MDhkZTkyOWJkMmZmYTY1OGJhYzY1OWYwYzViZGQwOTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.FWoCI-9Uj7Ci_o59IZEHUyQVUcgHsYN6t-HTQyzzWAg) 多选漏选
> 
> 钱包请截取这个路径下的 profile -> social profiles -> wallet 的截图

Done @zhangloveyan

2024-06-20 02:35 UTC, merged