feat: register user, username: zer0fire
openbuildxyz/Web3-Frontend-Bootcamp pull request #61
Opened 2024-06-04 12:32 UTC by zer0fire

报名

2024-06-06 15:54 UTC, BBK912 requested changes
格式错误，请将task1 的内容 移动到 task1 目录，之后其他任务亦是如此

2024-06-07 02:23 UTC, zer0fire commented
> 格式错误，请将task1 的内容 移动到 task1 目录，之后其他任务亦是如此

没找到 task1 目录，是否要自己新建？另外是否可以给出示意图？

2024-06-07 02:27 UTC, BBK912 commented
> > 格式错误，请将task1 的内容 移动到 task1 目录，之后其他任务亦是如此
> 
> 没找到 task1 目录，是否要自己新建？另外是否可以给出示意图？

是的，需要在自己ID文件夹下新建 
<img width="246" alt="image" src="https://github.com/openbuildxyz/Web3-Frontend-Bootcamp/assets/10484741/f0507973-bf42-4688-95e7-f987bc762530">

2024-06-07 02:28 UTC, zer0fire commented
> > > 格式错误，请将task1 的内容 移动到 task1 目录，之后其他任务亦是如此
> > 
> > 
> > 没找到 task1 目录，是否要自己新建？另外是否可以给出示意图？
> 
> 是的，需要在自己ID文件夹下新建 <img alt="image" width="246" src="https://private-user-images.githubusercontent.com/10484741/337500424-f0507973-bf42-4688-95e7-f987bc762530.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc3Mjc1NjEsIm5iZiI6MTcxNzcyNzI2MSwicGF0aCI6Ii8xMDQ4NDc0MS8zMzc1MDA0MjQtZjA1MDc5NzMtYmY0Mi00Njg4LTk1ZTctZjk4N2JjNzYyNTMwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjA3VDAyMjc0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTkzMTgxYjZhNzY1YzRhMjJhOWFjOWFhMTljZjJmYWM2ODc1MGE3MGUxMzgwYzM2Yjc1NjlmZjlkMDUyYTA3NWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.9X0AduIEuBTcDGwb_IKukzjRlsjYeBkih2ggMoDq5qY">

谢谢，已经改好了

2024-06-07 02:30 UTC, BBK912 commented
> > > > 格式错误，请将task1 的内容 移动到 task1 目录，之后其他任务亦是如此
> > > 
> > > 
> > > 没找到 task1 目录，是否要自己新建？另外是否可以给出示意图？
> > 
> > 
> > 是的，需要在自己ID文件夹下新建 <img alt="image" width="246" src="https://private-user-images.githubusercontent.com/10484741/337500424-f0507973-bf42-4688-95e7-f987bc762530.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc3Mjc1NjEsIm5iZiI6MTcxNzcyNzI2MSwicGF0aCI6Ii8xMDQ4NDc0MS8zMzc1MDA0MjQtZjA1MDc5NzMtYmY0Mi00Njg4LTk1ZTctZjk4N2JjNzYyNTMwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjA3VDAyMjc0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTkzMTgxYjZhNzY1YzRhMjJhOWFjOWFhMTljZjJmYWM2ODc1MGE3MGUxMzgwYzM2Yjc1NjlmZjlkMDUyYTA3NWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.9X0AduIEuBTcDGwb_IKukzjRlsjYeBkih2ggMoDq5qY">
> 
> 谢谢，已经改好了

钱包地址 检测一下 格式不对

2024-06-07 02:34 UTC, zer0fire commented
> > > > > 格式错误，请将task1 的内容 移动到 task1 目录，之后其他任务亦是如此
> > > > 
> > > > 
> > > > 没找到 task1 目录，是否要自己新建？另外是否可以给出示意图？
> > > 
> > > 
> > > 是的，需要在自己ID文件夹下新建 <img alt="image" width="246" src="https://private-user-images.githubusercontent.com/10484741/337500424-f0507973-bf42-4688-95e7-f987bc762530.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc3Mjc1NjEsIm5iZiI6MTcxNzcyNzI2MSwicGF0aCI6Ii8xMDQ4NDc0MS8zMzc1MDA0MjQtZjA1MDc5NzMtYmY0Mi00Njg4LTk1ZTctZjk4N2JjNzYyNTMwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjA3VDAyMjc0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTkzMTgxYjZhNzY1YzRhMjJhOWFjOWFhMTljZjJmYWM2ODc1MGE3MGUxMzgwYzM2Yjc1NjlmZjlkMDUyYTA3NWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.9X0AduIEuBTcDGwb_IKukzjRlsjYeBkih2ggMoDq5qY">
> > 
> > 
> > 谢谢，已经改好了
> 
> 钱包地址 检测一下 格式不对

已修复，按照这个地址填写

![image](https://github.com/openbuildxyz/Web3-Frontend-Bootcamp/assets/26370252/e166bf0c-5819-43b8-a388-0d6ba5ea1274)

2024-06-07 02:35 UTC, BBK912 approved these changes

2024-06-07 02:36 UTC, merged