Task2:xiaodingmao
openbuildxyz/Web3-Frontend-Bootcamp pull request #627
Opened 2024-06-14 13:25 UTC by xiaodingmao

2024-06-16 08:46 UTC, majoson-chen requested changes
修改

2024-06-20 03:12 UTC, zhangloveyan commented
简单题请用自己的话表述，不要用 gpt 生成

2024-08-30 17:22 UTC, ourai commented
因超过截止时间（2024 年 7 月 16 日 23 时 59 分 59 秒）仍未修改问题，故视为放弃继续学习而暂且关掉 PR，若要继续学习就重新打开并做修改。

2024-08-30 17:22 UTC, closed without merging

2024-08-30 17:22 UTC, xiaodingmao commented
谢谢，已收到