task1: Joejo
openbuildxyz/Web3-Frontend-Bootcamp pull request #633
Opened 2024-06-14 14:48 UTC by Joejo

![image](https://github.com/openbuildxyz/Web3-Frontend-Bootcamp/assets/5770995/2d8df00d-964c-4972-9d57-09b74d413e55)

2024-06-16 05:21 UTC, ourai requested changes
请在自己文件夹里提交

2024-06-18 08:34 UTC, Joejo commented
> 请在自己文件夹里提交

已调整，谢谢 @ourai

2024-06-18 08:48 UTC, ourai requested changes
运行报错，请好好自测下。

2024-06-27 09:10 UTC, Joejo commented
> 运行报错，请好好自测下。



不可能啊，我这运行好好的呀，辛苦您再看看

2024-07-12 07:36 UTC, Joejo commented
> 运行报错，请好好自测下。

已修复 @ourai

2024-07-12 08:45 UTC, ourai approved these changes

2024-07-12 08:45 UTC, merged