task1:Hazel
openbuildxyz/Web3-Frontend-Bootcamp pull request #648
Opened 2024-06-15 10:34 UTC by dreamahouse

task1:Hazel

2024-06-15 10:39 UTC, dreamahouse commented
<img width="678" alt="image" src="https://github.com/openbuildxyz/Web3-Frontend-Bootcamp/assets/13810500/f3ea1e03-7079-4daf-a035-5df96a7358e2">

2024-06-15 14:14 UTC, ourai requested changes
删掉最后一个数据后刷新页面又会出现

2024-06-15 15:49 UTC, dreamahouse commented
bug已改

2024-06-16 03:21 UTC, ourai approved these changes

2024-06-16 03:22 UTC, merged