task1:bcma2333
openbuildxyz/Web3-Frontend-Bootcamp pull request #711
Opened 2024-06-16 14:55 UTC by bcma2333

## PR规范

注册的 PR，命名为 `init: user-name`，例如 `init: Beavnvvv`

提交 task 的 PR，命名为 `task[n]: user-name`，例如： `task0: Beavnvvv`

需要编写网页的 `task`，请在描述中上传效果截图。

**请不要把报名和提交TASK的内容合并到一起，也不要将多个TASK放到一起提交！**  
**请不要把报名和提交TASK的内容合并到一起，也不要将多个TASK放到一起提交！**  
**请不要把报名和提交TASK的内容合并到一起，也不要将多个TASK放到一起提交！**

2024-06-17 01:48 UTC, ourai requested changes
完成状态刷新后消失且回显顺序有问题，请完整自测下。

2024-06-18 12:37 UTC, bcma2333 commented
雷叔，修改完了，再review一下哈

2024-06-19 02:53 UTC, ourai requested changes
把 task 2 拆出去

2024-06-19 11:54 UTC, bcma2333 commented
不好意思啊，没注意到把task2也合并进来了。已更改。

2024-06-21 02:36 UTC, ourai approved these changes

2024-06-21 02:37 UTC, merged