task3:jerryq1
openbuildxyz/Web3-Frontend-Bootcamp pull request #731
Opened 2024-06-17 08:12 UTC by jerryq1

## PR规范

注册的 PR，命名为 `init: user-name`，例如 `init: Beavnvvv`

提交 task 的 PR，命名为 `task[n]: user-name`，例如： `task0: Beavnvvv`

需要编写网页的 `task`，请在描述中上传效果截图。

**请不要把报名和提交TASK的内容合并到一起，也不要将多个TASK放到一起提交！**  
**请不要把报名和提交TASK的内容合并到一起，也不要将多个TASK放到一起提交！**  
**请不要把报名和提交TASK的内容合并到一起，也不要将多个TASK放到一起提交！**

2024-06-18 03:23 UTC, ourai requested changes
不要删除 task 1 和 task 2 相关文件

2024-06-20 02:42 UTC, jerryq1 commented
按要求加回上去了,麻烦ourai

2024-06-20 03:48 UTC, ourai requested changes
这个 PR 只提交 task 3 的文件，task 2 的在相应的 PR 处理。

2024-06-23 07:18 UTC, jerryq1 commented
可以帮忙把task2项目合并一下吗，还处于bug的状态，那个合并了之后我再pr一下task3

2024-06-25 03:03 UTC, ourai commented
> 可以帮忙把task2项目合并一下吗，还处于bug的状态，那个合并了之后我再pr一下task3

需要 @zhangloveyan 看下 #620

2024-07-05 10:10 UTC, linghuccc commented
> 可以帮忙把task2项目合并一下吗，还处于bug的状态，那个合并了之后我再pr一下task3

Task 3 应该和 task 2 独立，不应该会互相影响。

2024-07-05 12:01 UTC, ourai commented
> > 可以帮忙把task2项目合并一下吗，还处于bug的状态，那个合并了之后我再pr一下task3
> 
> 需要 @zhangloveyan 看下 #620

那个 PR 已经合了，你把这个 PR 对应的分支同步下上游代码。

2024-07-05 12:28 UTC, linghuccc commented
@jerryq1 请重新提交一个新的 task3 PR，这个 PR 前面的 commit 因为动了 task1 和 task2 的文件，不能使用，谢谢。

2024-07-05 12:28 UTC, closed without merging