Task3：xiangnuans
openbuildxyz/Web3-Frontend-Bootcamp pull request #753
Opened 2024-06-18 13:37 UTC by xiangnuans

## PR规范

注册的 PR，命名为 `init: user-name`，例如 `init: Beavnvvv`

提交 task 的 PR，命名为 `task[n]: user-name`，例如： `task0: Beavnvvv`

需要编写网页的 `task`，请在描述中上传效果截图。

**请不要把报名和提交TASK的内容合并到一起，也不要将多个TASK放到一起提交！**  
**请不要把报名和提交TASK的内容合并到一起，也不要将多个TASK放到一起提交！**  
**请不要把报名和提交TASK的内容合并到一起，也不要将多个TASK放到一起提交！**

2024-07-01 02:35 UTC, linghuccc requested changes
task3 只需要提交最主要的 3 份合约文件和上架NFT、购买NFT的交易哈希，请不要提交其他无关文件，谢谢

2024-07-01 03:53 UTC, xiangnuans commented
我把编译文件删除了，但目前是保留了脚本和初始化项目的文件，再看看哈

2024-07-04 07:11 UTC, linghuccc requested changes
1. 请提供上架 NFT 哈希；
2. 买家，卖家请使用不同地址；
3. 购买哈希显示的编程实现，与代码不符。

请修改，谢谢

2024-07-04 08:22 UTC, xiangnuans commented
1、3两点，pr提交里已经说明清楚了
2. 根据作业要求，并没有说不让用同一个账户，所以是符合作也要求的
<img width="580" alt="image" src="https://github.com/openbuildxyz/Web3-Frontend-Bootcamp/assets/24558814/67383599-a7c6-42d5-a205-a2a54e884df9">

2024-07-04 08:23 UTC, merged