task3: C3V4N
openbuildxyz/Web3-Frontend-Bootcamp pull request #754
Opened 2024-06-18 13:58 UTC by keyding

## Contracts

[ERC20](https://github.com/keyding/Web3-Frontend-Bootcamp/blob/fd25d6529ad70f321a8d6eab96db86266f4100dd/members/keyding/task3/src/Token.sol)

[ERC721](https://github.com/keyding/Web3-Frontend-Bootcamp/blob/fd25d6529ad70f321a8d6eab96db86266f4100dd/members/keyding/task3/src/NFT.sol)

[NFTMarket](https://github.com/keyding/Web3-Frontend-Bootcamp/blob/fd25d6529ad70f321a8d6eab96db86266f4100dd/members/keyding/task3/src/Marketplace.sol)

## Contract Interactive

### My Test Wallet

Address: 
[0xa831eeEFD053bfCa2E70293E2e0DA8660fca13Fa](https://sepolia.etherscan.io/address/0xa831eeefd053bfca2e70293e2e0da8660fca13fa)

### Mint NFT

Transaction Hash:
[0xca6956fe8a4ed107d44561f6687f96b8b44e5588630ac10553c570f463952b47](https://sepolia.etherscan.io/tx/0xca6956fe8a4ed107d44561f6687f96b8b44e5588630ac10553c570f463952b47)

### List NFT

Transaction Hash:
[0x6e43cb617c3da49878521f3971c55b614a31ab5e146854f63ed9f4b6f5c4b4c6](https://sepolia.etherscan.io/tx/0x6e43cb617c3da49878521f3971c55b614a31ab5e146854f63ed9f4b6f5c4b4c6)

### Buy NFT

Transaction Hash:
[0x67cb83c4875eedc0755f8344d6ebad977ae0a40901324b9fadfd296558b7b262](https://sepolia.etherscan.io/tx/0x67cb83c4875eedc0755f8344d6ebad977ae0a40901324b9fadfd296558b7b262)

2024-07-01 02:34 UTC, linghuccc requested changes
task3 只需要提交最主要的 3 份合约文件和上架NFT、购买NFT的交易哈希，请不要提交其他无关文件，谢谢

2024-07-01 15:15 UTC, keyding commented
> task3 只需要提交最主要的 3 份合约文件和上架NFT、购买NFT的交易哈希，请不要提交其他无关文件，谢谢

OK, 已更新。感谢。

2024-07-02 01:09 UTC, keyding commented
> 买家和卖家请用不同账户地址

OK，已使用另外一个账户购买 NFT。已更新 Buy NFT Transaction Hash，谢谢。

2024-07-02 05:32 UTC, linghuccc requested changes
购买哈希和 approve 哈希写反了，请修改，谢谢

2024-07-02 05:35 UTC, linghuccc reviewed
你的文件夹命名其实是错误的，应该用 github 的 ID，而你用了 openBuild 的 ID，但是考虑到已经完成了好几个 task，就不用改了，只是提出来，让你知道一下

2024-07-02 06:04 UTC, keyding commented
> 购买哈希和 approve 哈希写反了，请修改，谢谢

OK，已修改。

2024-07-02 06:06 UTC, keyding commented
> 你的文件夹命名其实是错误的，应该用 github 的 ID，而你用了 openBuild 的 ID，但是考虑到已经完成了好几个 task，就不用改了，只是提出来，让你知道一下

是 members 下面的文件名吗？members 下的就是我的 GitHub 的 ID。PR 的名字确实是用的 openBuild 的。我可以把 PR 的名字改成 GitHub 的 ID

2024-07-02 06:09 UTC, keyding commented
已修正提交PR的用户名为 GitHub ID，感谢。

2024-07-02 12:18 UTC, linghuccc approved these changes

2024-07-02 12:19 UTC, linghuccc commented
你提交 PR 时的描述改了，但 Readme 里面的内容却没改，我帮你改了

2024-07-02 12:19 UTC, merged