task3: zer0fire
openbuildxyz/Web3-Frontend-Bootcamp pull request #759
Opened 2024-06-18 16:15 UTC by zer0fire

![image](https://github.com/openbuildxyz/Web3-Frontend-Bootcamp/assets/26370252/4b11f1d6-a359-4eb2-8c28-6039517d0148)

利用 ganache 在本地部署

2024-07-01 02:33 UTC, linghuccc requested changes
task3 只需要提交最主要的 3 份合约文件和上架NFT、购买NFT的交易哈希，请不要提交其他无关文件，谢谢

2024-07-01 10:28 UTC, zer0fire commented
> task3 只需要提交最主要的 3 份合约文件和上架NFT、购买NFT的交易哈希，请不要提交其他无关文件，谢谢

已修改

2024-07-01 16:10 UTC, linghuccc requested changes
上架NFT、购买NFT的交易哈希在哪里？

Readme.md 和 提交界面都没有看到

2024-07-01 18:16 UTC, zer0fire commented
> 上架NFT、购买NFT的交易哈希在哪里？
> 
> Readme.md 和 提交界面都没有看到

已补充
上架：0x09a06963b1ce42aae640ac1be4d5c88a2281e1ce6cebc5a541c7efc2f1b88be8
买入：0xff665231fc2a9a7e366e39a4d14ca4b7c99892cbce0c78759261aebf82fa3c2b

2024-07-02 05:24 UTC, linghuccc approved these changes

2024-07-02 05:24 UTC, merged