init: zhong-shanfu
openbuildxyz/Web3-Frontend-Bootcamp pull request #760
Opened 2024-06-18 19:05 UTC by zhong-shanfu

2024-06-19 01:21 UTC, ourai requested changes
只能修改自己文件夹的文件

2024-06-20 00:57 UTC, ourai requested changes
把 `package.json` 和 `package-lock.json` 也去掉。

2024-06-20 01:08 UTC, zhong-shanfu commented
已删除，谢谢审核

2024-06-20 03:33 UTC, ourai approved these changes

2024-06-20 03:36 UTC, merged