task1:sajakx
openbuildxyz/Web3-Frontend-Bootcamp pull request #767
Opened 2024-06-19 09:40 UTC by sajakx

2024-06-19 21:17 UTC, sunnydreamer commented
在 members/[github_id] 文件夹下按照 task[n] 的命名方式创建任务文件夹，如：task1、task2

2024-06-19 21:43 UTC, sunnydreamer requested changes
修改文件名：在 members/[github_id] 文件夹下按照 task[n] 的命名方式创建任务文件夹，如：task1、task2

2024-06-20 10:49 UTC, sunnydreamer requested changes
分离init任务和task1：请不要把报名和提交TASK的内容合并到一起，也不要将多个TASK放到一起提交

2024-06-20 22:26 UTC, sunnydreamer requested changes
请注意文件夹命名，不是taks1，task1

2024-06-21 17:15 UTC, ourai commented
@sajakx 请额外再补个报名的 PR，否则其他任务做了也不算数的。

2024-07-12 02:23 UTC, ourai requested changes
刷新后数据消失

2024-08-30 17:25 UTC, ourai commented
因超过截止时间（2024 年 7 月 16 日 23 时 59 分 59 秒）仍未修改问题，故视为放弃继续学习而暂且关掉 PR，若要继续学习就重新打开并做修改。

2024-08-30 17:25 UTC, closed without merging