task3: zhengjunxiang
openbuildxyz/Web3-Frontend-Bootcamp pull request #801
Opened 2024-06-20 14:45 UTC by zhengjunxiang

2024-07-01 02:13 UTC, linghuccc requested changes
task3 的提交，请局限在 task3 文件夹内

2024-07-21 17:13 UTC, zhengjunxiang commented
> task3 的提交，请局限在 task3 文件夹内，谢谢

已经修改，请查看

2024-07-22 03:24 UTC, linghuccc requested changes
1. function listNFT 函数中不应该有 string memory tokenUrl 参数（在 nftContract 和 tokenId 确定的情况下，tokenUrl 也是确定的）；
2. listNFT 时已经把 NFT 转到了 NFT Market 合约，purchaseNFT 时就不可能从targetNft.seller 转出 NFT，因为 targetNft.seller 已经没有 NFT 了。

请修改，修改过后记得更新哈希值，谢谢。

2024-08-30 17:28 UTC, ourai commented
因超过截止时间（2024 年 7 月 16 日 23 时 59 分 59 秒）仍未修改问题，故视为放弃继续学习而暂且关掉 PR，若要继续学习就重新打开并做修改。

2024-08-30 17:28 UTC, closed without merging