[task1]: react vite todo list
openbuildxyz/Web3-Frontend-Bootcamp pull request #82
Opened 2024-06-04 13:38 UTC by xiangnuans

2024-06-09 09:51 UTC, zhengqiuwan commented
> _ No description provided. _

麻烦提供一下task1运行截图

2024-06-09 14:22 UTC, xiangnuans commented
@zhengqiuwan 
![image](https://github.com/openbuildxyz/Web3-Frontend-Bootcamp/assets/24558814/cfef6e85-0370-4508-814f-9359138bc034)

2024-06-10 09:18 UTC, ourai requested changes
你的个人文件夹名字是错的，应该是 `xiangnuans`

2024-06-11 01:41 UTC, xiangnuans commented
@ourai 感谢review，已调整

2024-06-11 03:09 UTC, ourai approved these changes

2024-06-11 03:09 UTC, merged

2024-06-11 03:17 UTC, ourai commented
@xiangnuans 我在 https://github.com/openbuildxyz/Web3-Frontend-Bootcamp/commit/363d26ccc797465162f2ca3636ade926377c94e4 帮你把 #29 中合进去的错误文件夹名字改了，你进行下个任务提交前先同步下 `main` 分支代码。