task1:qimalan
openbuildxyz/Web3-Frontend-Bootcamp pull request #874
Opened 2024-06-24 07:29 UTC by qimalan

<img width="697" alt="Snipaste_2024-06-22_20-24-50" src="https://github.com/openbuildxyz/Web3-Frontend-Bootcamp/assets/83695230/529dbe64-0274-42f9-a13a-4f0821a9a4c0">

2024-06-25 03:37 UTC, ourai requested changes
不要删除 `readme.md`，否则合进去后会删掉已经合并的文件

2024-06-25 11:30 UTC, qimalan commented
> 不要删除 `readme.md`，否则合进去后会删掉已经合并的文件

每个 task 都要包含 “readme.md” 吗

2024-06-25 12:34 UTC, ourai commented
是你提交 PR 的方式有问题，可看这个视频 https://www.bilibili.com/video/BV11gVxeuE7Y/

2024-06-25 13:21 UTC, qimalan commented
> 是你提交 PR 的方式有问题，可看这个视频 https://www.bilibili.com/video/BV11gVxeuE7Y/

看完了。我报名的 init 已经合进去了，之后提交 task1 是不是提交的是 task1 文件夹跟 报名的“readme.md”；提交 task2 的话就是 task2 文件夹 + “readme.md” ？ 之前是本地创建 task1 分支后主动把 报名文件删除后再提交的

2024-06-26 02:06 UTC, ourai commented
> > 是你提交 PR 的方式有问题，可看这个视频 https://www.bilibili.com/video/BV11gVxeuE7Y/
> 
> 看完了。我报名的 init 已经合进去了，之后提交 task1 是不是提交的是 task1 文件夹跟 报名的“readme.md”；提交 task2 的话就是 task2 文件夹 + “readme.md” ？ 之前是本地创建 task1 分支后主动把 报名文件删除后再提交的

报名的 readme 已经合进去了，你新的 PR 里把它删除我如果合进去就是做了删除操作，会把已经合进去的报名 readme 删掉，所以你任何新的 PR 都不能直接用删除的方式干掉不属于当前 PR 的文件。

正确的提 PR 的方式是只做当前任务相关文件的增量操作。

针对你当前的情况，你在这个分支里把删掉的文件加回来，然后你 fork 的远程仓库同步最新代码，这样你这个 PR 里应该就不会有报名 readme 了。

2024-06-27 07:02 UTC, qimalan commented
> > > 是你提交 PR 的方式有问题，可看这个视频 https://www.bilibili.com/video/BV11gVxeuE7Y/
> > 
> > 
> > 看完了。我报名的 init 已经合进去了，之后提交 task1 是不是提交的是 task1 文件夹跟 报名的“readme.md”；提交 task2 的话就是 task2 文件夹 + “readme.md” ？ 之前是本地创建 task1 分支后主动把 报名文件删除后再提交的
> 
> 报名的 readme 已经合进去了，你新的 PR 里把它删除我如果合进去就是做了删除操作，会把已经合进去的报名 readme 删掉，所以你任何新的 PR 都不能直接用删除的方式干掉不属于当前 PR 的文件。
> 
> 正确的提 PR 的方式是只做当前任务相关文件的增量操作。
> 
> 针对你当前的情况，你在这个分支里把删掉的文件加回来，然后你 fork 的远程仓库同步最新代码，这样你这个 PR 里应该就不会有报名 readme 了。

基于你的回答，我理解的提交 pr 的方式是：提交的 pr 的内容，是在已经合并的内容的基础上的增量内容，是这个意思吗。
以我为例：由于我的报名pr已经合并，所以我本地新建的 task1 分支是有报名的 readme.md 文件的，此时我只需要新建task1 文件夹，完成内容后，提交pr就行了。如果我完成task2的时候我的 task1也已合并，那么我提交task2 的时候，内容是 readme.md + task1 文件夹 + task2 文件夹，我理解的对吗，感谢🙏回答，不会怎么会使用 git，以上理解是问过 gpt 后的理解

2024-08-30 17:33 UTC, closed without merging