task3:LittleMoreInteresting
openbuildxyz/Web3-Frontend-Bootcamp pull request #878
Opened 2024-06-24 11:55 UTC by LittleMoreInteresting

task3

2024-06-30 16:21 UTC, linghuccc requested changes
使用 ERC20 代币买 NFT，而不是 ETH

2024-06-30 16:21 UTC, LittleMoreInteresting commented
自动回复邮件。您好，感谢您的来信。我会尽快查阅您的邮件并及时给您回复。

2024-07-01 05:27 UTC, LittleMoreInteresting commented
permitBuy  方法使用的是ERC20 代币购买

2024-07-01 16:07 UTC, linghuccc reviewed
function permitBuy 里面的 amount 参数，有什么存在的意义？

2024-07-03 02:26 UTC, linghuccc approved these changes

2024-07-03 02:26 UTC, merged