task3: coderprepares
openbuildxyz/Web3-Frontend-Bootcamp pull request #917
Opened 2024-06-25 20:02 UTC by coderprepares

## PR规范

注册的 PR，命名为 `init: user-name`，例如 `init: Beavnvvv`

提交 task 的 PR，命名为 `task[n]: user-name`，例如： `task0: Beavnvvv`

需要编写网页的 `task`，请在描述中上传效果截图。

**请不要把报名和提交TASK的内容合并到一起，也不要将多个TASK放到一起提交！**  
**请不要把报名和提交TASK的内容合并到一起，也不要将多个TASK放到一起提交！**  
**请不要把报名和提交TASK的内容合并到一起，也不要将多个TASK放到一起提交！**

2024-07-01 03:02 UTC, linghuccc requested changes
task3 只需要提交最主要的 3 份合约文件和上架NFT、购买NFT的交易哈希，请不要提交其他无关文件，谢谢

2024-07-01 03:38 UTC, coderprepares commented
已修改

2024-07-01 16:04 UTC, linghuccc requested changes
List NFT 时未检查 price > 0，会导致 list 行为无效，逻辑错误。

2024-08-30 17:38 UTC, ourai commented
因超过截止时间（2024 年 7 月 16 日 23 时 59 分 59 秒）仍未修改问题，故视为放弃继续学习而暂且关掉 PR，若要继续学习就重新打开并做修改。

2024-08-30 17:38 UTC, closed without merging