task3: JeremyZ
openbuildxyz/Web3-Frontend-Bootcamp pull request #919
Opened 2024-06-26 03:04 UTC by warku123

# Task3

**由于Task1 PR修改了文件夹名，因此需要先对task1 PR进行合并！！！**
Task1: https://github.com/openbuildxyz/Web3-Frontend-Bootcamp/pull/517

| 说明       | 地址                                                         |
| ---------- | ------------------------------------------------------------ |
| PGT(token) | 0x11157f373FEceE53cD44DC89e2a6a463d27056db                   |
| PFT(NFT)   | 0xDDB391E6fCe3D4E24466fDe63DCf2118970FC4d6                   |
| NFTMarket  | 0x11e02fFE180A74ee63AA7207C0e530Df01167E75                   |
| 上架 NFT   | 0xb8cf4d920756a90937458d035025dbe2c302a0adffcd6fe48c394e5491ec2053 |
| 购买 NFT   | 0x533a5bd44779153da8cad4ed63175868bd60fa1d2f01af14e343131bc1811f4e |

2024-07-01 03:03 UTC, linghuccc requested changes
task3 的 PR，请不要对其他 task 的文件进行修改，谢谢

2024-07-04 04:58 UTC, warku123 commented
> task3 的 PR，请不要对其他 task 的文件进行修改，谢谢

这边没有修改其他task的文件，因为之前修改了文件夹名称，为了防止冲突，我rebase了task1的分支，导致看到的commit是这样的，task1修改可以参照下面：
Task1: https://github.com/openbuildxyz/Web3-Frontend-Bootcamp/pull/517

2024-07-04 05:08 UTC, linghuccc requested changes
“为了防止冲突，我rebase了task1的分支”

说明你还是没有明白如何正确提交，请去 B 站多看几遍 欧雷 关于提交 PR 的视频，谢谢

2024-07-04 06:45 UTC, warku123 commented
> “为了防止冲突，我rebase了task1的分支”
> 
> 说明你还是没有明白如何正确提交，请去 B 站多看几遍 欧雷 关于提交 PR 的视频，谢谢

我为了task1和task3并行，所以在task1修改文件夹名称后，task3 rebase了task1的分支，这样子我task3的修改也是在新文件夹名上修改的，merge之后才不会导致文件夹名称的冲突，如果真的需要，我就直接从task1新建分支我重新开一个merge吧

2024-07-04 06:48 UTC, warku123 commented
没新开PR的原因是因为我怕PR开启时间不对影响最后的任务奖励判断

2024-07-04 07:04 UTC, linghuccc requested changes
提交 PR 的时间，不会影响（只要在期限之内提交，都一样）；能否正确的提交 PR，才是真正会影响的。

2024-07-04 07:38 UTC, closed without merging

2024-07-04 07:42 UTC, warku123 commented
> 提交 PR 的时间，不会影响（只要在期限之内提交，都一样）；能否正确的提交 PR，才是真正会影响的。

新开了PR：https://github.com/openbuildxyz/Web3-Frontend-Bootcamp/pull/1078