task3: K-tang-mkv
openbuildxyz/Web3-Frontend-Bootcamp pull request #923
Opened 2024-06-26 06:42 UTC by K-tang-mkv

# K-tang-mkv's task 3

文件说明：

| 文件名 | Sepolia 地址 | 说明 |
| --- | --- | --- |
| ERC20Gant.sol | 0x0349BB01Ea55E5BcB598e3EC859c2a9289B37Fe1 | ERC20 token 合约|
| NFT.sol | 0x534B6786612674FBa5A0bd0AB7cFc443bF372991 | NFT 合约 |
| NFTMarket.sol | 0x626bB5145B0e90dfBAE0F3724A5c1185A74a6345 | NFTMarket 合约 |

| 动作 | 交易哈希 |
| --- | --- |
| 上架NFT | 0x709fd35a3535b7036ed83f6b7c43f961d5afb67e62c382097c5dbd569a77714b |
| 购买NFT | 0x7c67fa5a50ddea131fe7794dfc3bf505240269349011217ff1251f893cdf66ae |

2024-07-01 03:09 UTC, linghuccc requested changes
缺乏各种必要的检查，比如 buyNFT 的时候，没有检查 listing 是否存在

2024-07-05 08:52 UTC, ourai commented
#966 #971 这俩 PR 如果合并的话：
1. 先合并那俩其中一个，当前 task 3 的 PR 会被标记为已合并后关闭；
2. 先合并当前 task 3 的 PR，则合并那俩 PR 的任何一个都会把这个 PR 中的文件删除。

2024-07-05 11:05 UTC, K-tang-mkv commented
> #966 #971 这俩 PR 如果合并的话：
> 
> 1. 先合并那俩其中一个，当前 task 3 的 PR 会被自动标记为已合并后关闭；
> 2. 先合并当前 task 3 的 PR，则合并那俩 PR 的任何一个都会把这个 PR 中的文件删除。
> 
> @K-tang-mkv 你需要根据提交规范正确处理。

可以关了，重新pr吗

2024-07-05 11:58 UTC, ourai commented
> > #966 #971 这俩 PR 如果合并的话：
> > 
> > 1. 先合并那俩其中一个，当前 task 3 的 PR 会被自动标记为已合并后关闭；
> > 2. 先合并当前 task 3 的 PR，则合并那俩 PR 的任何一个都会把这个 PR 中的文件删除。
> > 
> > @K-tang-mkv 你需要根据提交规范正确处理。
> 
> 可以关了，重新pr吗

把那俩重新提吧，**用正确的方式**。

2024-07-05 16:48 UTC, closed without merging