task3: joy-joy-joy-joy-joy-joy-joy
openbuildxyz/Web3-Frontend-Bootcamp pull request #999
Opened 2024-06-30 05:27 UTC by joy-joy-joy-joy-joy-joy-joy

交易的哈希在本task的readme.md中

2024-07-01 04:55 UTC, linghuccc requested changes
你的 sellerProceeds = _order.price - fee，paymentToken.allowance(msg.sender, address(this)) 就不应该 >= (_order.price+fee), 而是 >= _order.price

2024-07-01 09:35 UTC, joy-joy-joy-joy-joy-joy-joy commented
> sellerProceeds = _order.price - fee，那么 paymentToken.allowance(msg.sender, address(this)) 就不应该 >= (_order.price+fee), 而是 >= _order.price 才对

合约的费用在成交时从挂单者和买单者都抽成5%，例如挂单价格100token，买方实付105token，卖方实收95token，10token则归市场合约。

2024-07-01 09:47 UTC, joy-joy-joy-joy-joy-joy-joy commented
> sellerProceeds = _order.price - fee，那么 paymentToken.allowance(msg.sender, address(this)) 就不应该 >= (_order.price+fee), 而是 >= _order.price 才对

费用转账已经改成fee*2。

2024-07-02 02:13 UTC, joy-joy-joy-joy-joy-joy-joy commented
> 买家和卖家请使用不同地址，谢谢

哈希已经更新。

2024-07-02 05:09 UTC, linghuccc approved these changes

2024-07-02 05:09 UTC, merged